config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'novels#index'
  resources :novels do
		resources :chapters, except: [:index] do
			 resources :comments, except: [:index,:show]
		end
  end

 


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
	belongs_to :user
	belongs_to :novel
	has_many :comments
	validates :chap, presence: true,  numericality: { only_integer: true }
	validates :name, presence: true, length: { minimum: 3, maximum: 25 }
	validates :content, presence: true, length: { minimum: 3 }
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :chapter
end

app/models/novel.rb
class Novel < ApplicationRecord
	has_many :chapters, dependent: :destroy
	has_many :users, through: :chapters
	accepts_nested_attributes_for :chapters
	validates :name, presence: true, length: { minimum: 3, maximum: 25 }, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :chapters, dependent: :destroy
	has_many :novels, through: :chapters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :novels

  def novels
  	@novels = Novel.all
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
	skip_before_action :authenticate_user!, only: [:show]
	before_action :set_novel
	before_action :set_chapter, except: [:new, :create]
	
	def new
		@chapter = Chapter.new
	end

	def create
		@user = User.all
		@chapter = Chapter.new(chapter_params)
		@chapter.user = current_user
		if @chapter.save
			redirect_to novel_chapter_path(@novel, @chapter)
		else
			render 'new'
		end
	end

	def edit

	end

	def update
		if @chapter.update(chapter_params)
			redirect_to novel_chapter_path(@novel, @chapter)
		else
			render 'edit'
		end
	end

	def show
		@chapters = Chapter.all
		@comment = Comment.new
	end

	def destroy
		@chapter.destroy
		redirect_to novel_path(@novel.id)
	end

	def form_comments
		 respond_to do |format|
      format.js  { render partial: 'comments/form_comments' }
     end		
	end

	private

	def set_novel
		@novel = Novel.find(params[:novel_id])
	end

	def set_chapter
		@chapter = Chapter.find(params[:id])
	end

	def chapter_params
		params.require(:chapter).permit(:chap, :name, :content, :user_id, :novel_id)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_params
	before_action :set_comment, only: [:edit, :update]

	def new
		@comment = Comment.new
	end

	def create
		@comment = Comment.new(comment_params)
		if @comment.save
			flash[:notice] = "success"
			redirect_to novel_chapter_path(@chapter.novel.id, @chapter)
		else
			flash[:danger] = "fail"
			redirect_to novel_chapter_path(@chapter.novel.id, @chapter)
		end
	end

	def edit

	end

	def update
		if @comment.update(comment_params)
			redirect_to novel_chapter_path(@chapter.novel.id, @chapter)
		else
			redirect_to root_path
		end
	end

	private

	def set_comment
		@comment = Comment.find(params[:id])
	end

	def set_params
		@novel = Novel.find(params[:novel_id])
		@chapter = Chapter.find(params[:chapter_id])
	end

	def comment_params
		params.require(:comment).permit(:email, :content, :chapter_id)
	end
end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
	skip_before_action :authenticate_user!, only: [:index, :show]
	before_action :find_chap, only: [:index, :show]
	before_action :set_novel, except: [:index, :new, :create]

	def index
		@novels = Novel.all
		@chapters = Chapter.all
	end

	def new
		@novel = Novel.new
	end

	def create
		@novel = Novel.new(novel_params)
		if @novel.save
			redirect_to @novel
		else
			render 'new'
		end
	end

	def edit

	end

	def update
		if @novel.update(novel_params)
			redirect_to @novel
		else
			render 'edit'
		end
	end

	def show
		@novels = Novel.all
	end

	def destroy
		@novel.destroy
		redirect_to root_path
	end

	private

	def novel_params
		params.require(:novel).permit(:name)
	end

	def set_novel
		@novel = Novel.find(params[:id])
	end

	def find_chap
		@chapters = Chapter.where(novel_id: params[:id]).find_each
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/novels_helper.rb
module NovelsHelper
end

app/views/chapters/_comments.html.erb
<div class="row">
	<div class="col s12">
		<ul class="collection">
			<% @chapter.comments.order('id asc').each do |comment| %>
				<li class="collection-item">
					<h5><%= comment.email %></h5>  <br>
				 	<span><em><%= comment.content %></em></span> <br>
				 	<small><%= time_ago_in_words(comment.created_at) %></small>
				 	<small><%= link_to 'Edit', edit_novel_chapter_comment_path(@novel, @chapter, comment) %></small>
				</li>
			<% end %>
		</ul>
	</div>
</div>

app/views/chapters/_form.html.erb
<% if @chapter.new_record? %>
	<h1>New Chapter</h1>
<% else %>
	<h1>Edit Chapter</h1>
<% end %>

<%= form_for [@novel, @chapter] do |f| %>

	<%= f.label 'Chapter' %> <br>
	<%= f.text_field :chap, autofocus: true %> <br>

	<%= f.label :name %> <br>
	<%= f.text_field :name %> <br>

	<%= f.label :content %> <br>
	<%= f.text_area :content, class: "materialize-textarea" %> <br>

	<%= f.hidden_field(:novel_id, :value => @novel.id) %>

	<%= @chapter.new_record? ? (f.button 'New Chapter', class: "waves-effect waves-light btn right") 
													: (f.button 'Edit Chapter', class: "waves-effect waves-light btn right") %>

<% end %>

app/views/chapters/edit.html.erb
<%= render 'shared/errors', obj: @chapter %>
<%= render 'form' %>

app/views/chapters/new.html.erb
<%= render 'shared/errors', obj: @chapter %>
<%= render 'form' %>

app/views/chapters/show.html.erb
<h1><%= @chapter.novel.name %></h1>
<h3><%= "#{@chapter.chap} - #{@chapter.name}" %></h3>
<p><%= simple_format(@chapter.content) %></p>

<div class="row center">
	<% if @chapter != @novel.chapters.min  %>
		<%= link_to "<- Back", novel_chapter_path(@novel, @chapter.id - 1) %>
	<% end %>

	<% if @chapter != @novel.chapters.max %>
		<%= link_to "Next ->", novel_chapter_path(@novel, @chapter.id + 1) %>
	<% end %>
</div>

<p>There is <%= pluralize(@chapter.comments.count, "comment") %> for this chapter</p>

<div class="row">
	<div class="col s2"></div>
	<div class="col s8 new_comment">
		<%= render  'comments/form_comments' %>
	</div>
	<div class="col s2"></div>
</div>

<%= render 'comments' %>

app/views/comments/_form_comments.html.erb
<%= form_for [@novel, @chapter, @comment] do |f| %>

	<%= f.hidden_field(:chapter_id, :value => @chapter.id) %>

	<%= f.label :email %>
	<%= f.email_field :email %>

	<%= f.label :content %>
	<%= f.text_area :content, class: "materialize-textarea" %><br>

	<%= f.button "New Comment", class: "waves-effect waves-light right btn pad-top" %>

<% end %> 

app/views/comments/edit.html.erb
<%= render 'form_comments' %>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2014 Copyright Text
    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content">
	<% @novels.each do |novel| %>
		<li class="txt2"><%= link_to novel.name, novel_path(novel.id) %></li>
	<% end %>
</ul>

<ul class="sidenav" id="mobile-demo">
    <li><a href="sass.html">Sass</a></li>
    <li><a href="badges.html">Components</a></li>
    <li><a href="collapsible.html">Javascript</a></li>
    <li><a href="mobile.html">Mobile</a></li>
</ul>

<nav class="transparent z-depth-0">
  <div class="nav-wrapper col s12">
  	<a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
  	<ul class="txt-color hide-on-med-and-down">
  		<li class="col s4"><%= link_to 'Home', root_path %></li>
  		<li class="col s4"><a class="dropdown-trigger" href="#!" data-target="dropdown1">Novels List<i class="material-icons right">arrow_drop_down</i></a></li>
			<li class="col s4">
				<%= user_signed_in? ? (link_to "Logout", destroy_user_session_path, method: :delete) : (link_to "login", new_user_session_path) %>
			</li>	
  	</ul>
  </div>
</nav>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NovelsApp</title>
    <%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<header>
  		<div class="parallax-container">
  			<div class="parallax"><%= image_tag("parallax1.jpg") %></div>
  			  <div class="caption">
            <h1>Novel App</h1>
          </div>
			</div>
			<div class="section white">
			<div class="row container">
				<%= render 'layouts/navbar' %>
			</div>
  	</header>
  	
		<main class="container pad-bot">
			<%= yield %>
		</main>
	
  	<%= render 'layouts/footer' %>
  	</div>
  </body>
</html>

app/views/novels/_form.html.erb
<% if @novel.new_record? %>
	<h1>New Novel</h1>
<% else %>
	<h1>Edit novel name</h1>
<% end %>

<%= form_for @novel do |f| %>

	<%= f.label :name %>
	<%= f.text_field :name  %>

	<%= @novel.new_record? ? (f.button "New Novel", class: "waves-effect waves-light btn right") : (f.submit 'Edit Name', class: "waves-effect waves-light btn right") %>

<% end %>

app/views/novels/edit.html.erb
<%= render 'shared/errors', obj: @novel %>
<%= render 'form' %>

app/views/novels/index.html.erb
<ul class="collection">
	<% @chapters.order(id: :desc).each do |chapter| %>
		<li class="collection-item">
			<h4 class="header"><%= link_to chapter.name, novel_chapter_path(chapter.novel.id, chapter.id) %></h4>
			<p class="grey-text text-darken-3 lighten-3 txt"><%= truncate(chapter.content, :length => 400) %></p>
			<small>Posted by: <%= chapter.user.admin? ? "Admin" : chapter.user.fname %></small>
			<small><%= link_to chapter.novel.name, novel_path(chapter.novel.id) %></small>
			<small>Created: <%= chapter.created_at.strftime("%F") %></small>
			<small>Posted: <%= time_ago_in_words(chapter.created_at) %></small>
		</li>
	<% end %>
</ul>


			




app/views/novels/new.html.erb
<%= render 'shared/errors', obj: @novel %>
<%= render 'form' %>

app/views/novels/show.html.erb
<h1><%= @novel.name %></h1>
<p align="center">List of Chapters</p>

<ul>
	<% @chapters.each do |chapter| %>
		<li>
			<%= link_to "#{chapter.chap} - #{chapter.name}", novel_chapter_path(chapter.novel.id, chapter.id) %>
			<% if user_signed_in? && current_user.admin %>
 				<%= link_to "Delete Chapter", novel_chapter_path(chapter.novel.id, chapter.id), method: :delete, data: { confirm: "Are you sure you wan to delete #{chapter.name}"} %>
			<% end %>
		</li>
	<% end %>
</ul>

<% if user_signed_in? && current_user.admin %>
 <%= link_to "New chapter", new_novel_chapter_path(@novel) %>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<%= pluralize(obj.errors.count, "error" ) %>
	<ul>
		<% obj.errors.full_messages.each do |error| %>
		<li><%= error %></li>
		<% end %>
	</ul>
<% end %>
